language: python

dist: xenial

python:
    - 3.6

before_install:
    - python -m pip install --upgrade pip

install:
    - pip install -r scripts/requirements.txt
    - pip install -r tests/requirements.txt

script:
    - pytest --cov=./